# ruff: noqa: RUF001
"""Human-readable labels for genre codes."""

GENRE_NAMES: dict[str, str] = {
    "about_musicians": "Биографии и мемуары: музыканты, композиторы, художники",
    "adv_animal": "Природа и животные",
    "adv_geo": "Путешествия и география",
    "adv_history": "Исторические приключения",
    "adv_indian": "Вестерн, про индейцев",
    "adv_maritime": "Морские приключения",
    "adv_modern": "Приключения в современном мире",
    "adv_story": "Авантюрный роман",
    "adventure": "Приключения",
    "adventure_fantasy": "Приключенческое фэнтези",
    "antique": "antique",
    "antique_ant": "Античная литература",
    "antique_east": "Древневосточная литература",
    "antique_european": "Европейская старинная литература",
    "antique_myths": "Мифы. Легенды. Эпос",
    "antique_russian": "Древнерусская литература",
    "aphorisms": "Афоризмы, цитаты",
    "architecture_book": "Скульптура и архитектура",
    "art_criticism": "Искусствоведение",
    "art_world_culture": "Мировая художественная культура",
    "asian_fantasy": "Азиатское фэнтези (уся, сянься, культивация)",
    "astrology": "Астрология и хиромантия",
    "auto_business": "Автодело",
    "auto_regulations": "Автомобили и ПДД",
    "banking": "Финансы",
    "boyar_anime": "Бояръ-аниме",
    "child_adv": "Детская проза: приключения",
    "child_adv_animal": "Детская проза: о животных и природе",
    "child_classical": "Классическая детская литература",
    "child_det": "Детские остросюжетные: прочее",
    "child_det_animal_detectives": "Детские детективы: животные-сыщики",
    "child_det_children_detectives": "Детские детективы: дети-сыщики",
    "child_det_other": "Детские детективы: прочее",
    "child_dramaturgy": "Драматургия для детей и подростков",
    "child_education": "Детская образовательная литература",
    "child_folklore": "Детский фольклор",
    "child_prose": "Детская проза: прочее",
    "child_prose_history": "Детская проза: военная и историческая",
    "child_prose_humor": "Детская проза: юмористическая, о школе и школьниках",
    "child_prose_romantic": "Детская проза: романтическая",
    "child_sf": "Детская фантастика: прочее",
    "child_sf_fantasy": "Детская фантастика: фэнтези",
    "child_sf_horror": "Детская фантастика: ужасы и мистика",
    "child_sf_hronoopera": "Детская фантастика: темпоральная, попаданцы",
    "child_sf_space": "Детская фантастика: космические приключения, пришельцы",
    "child_tale": "Литературные и народные сказки: прочее",
    "child_tale_foreign_writers": "Сказки зарубежных писателей",
    "child_tale_rus": "Русские сказки",
    "child_tale_russian_writers": "Сказки отечественных писателей",
    "child_verse": "Стихи для детей и подростков",
    "children": "Детская литература: прочее",
    "cine": "Кино",
    "comedy": "Комедия",
    "comics": "Комиксы",
    "comp_db": "Программирование, программы, базы данных",
    "comp_hard": "Компьютерное 'железо' (аппаратное обеспечение), цифровая обработка сигналов",
    "comp_osnet": "ОС и Сети",
    "comp_www": "ОС и Сети, интернет",
    "computer_translation": "Машинный перевод",
    "computers": "Зарубежная компьютерная, околокомпьютерная литература",
    "dark_fantasy": "Тёмное фэнтези",
    "design": "Искусство и Дизайн",
    "det_action": "Боевик",
    "det_artifact": "Артефакт-детективы",
    "det_classic": "Классический детектив",
    "det_crime": "Криминальный детектив",
    "det_espionage": "Шпионский детектив",
    "det_hard": "Крутой детектив",
    "det_history": "Исторический детектив",
    "det_irony": "Иронический детектив",
    "det_lady": "Дамский детективный роман",
    "det_maniac": "Про маньяков",
    "det_other": "Детективы и триллеры: прочее",
    "det_police": "Полицейский детектив",
    "det_political": "Политический детектив",
    "det_su": "Советский детектив",
    "detective": "Детективы",
    "dorama": "Дорама",
    "drama": "Драма",
    "drama_antique": "Античная драма",
    "dramaturgy": "Драматургия",
    "dystopian": "Антиутопия",
    "economics": "Экономика",
    "economics_ref": "Деловая литература",
    "epic": "Былины, эпопея",
    "epistolary_fiction": "Эпистолярная проза",
    "equ_history": "История техники",
    "everyday_fantasy": "Бытовое фэнтези",
    "fairy_fantasy": "Мифологическое фэнтези",
    "family": "Семейные отношения",
    "fan_translation": "Любительский перевод",
    "fanfiction": "Фанфик",
    "fantasy_alt_hist": "Альтернативная история",
    "fantasy_det": "Фантастический детектив",
    "folk_songs": "Народные песни",
    "folk_tale": "Народные сказки",
    "folklore": "Фольклор, загадки folklore",
    "foreign_antique": "Средневековая классическая проза",
    "foreign_children": "Зарубежная литература для детей",
    "foreign_prose": "Зарубежная классическая проза",
    "foreign_sf": "Зарубежная фантастика и фэнтези",
    "geo_guides": "Путеводители, карты, атласы",
    "gothic_novel": "Готический роман",
    "great_story": "Роман, повесть",
    "historical_fantasy": "Историческое фэнтези",
    "home": "Домоводство",
    "home_collecting": "Коллекционирование",
    "home_cooking": "Кулинария",
    "home_crafts": "Хобби и ремесла",
    "home_diy": "Сделай сам",
    "home_entertain": "Развлечения",
    "home_garden": "Сад и огород",
    "home_health": "Здоровье",
    "home_pets": "Домашние животные",
    "home_sex": "Семейные отношения, секс",
    "home_sport": "Боевые искусства, спорт",
    "hronoopera": "Хроноопера",
    "humor": "Юмор",
    "humor_anecdote": "Анекдоты",
    "humor_prose": "Юмористическая проза",
    "humor_satire": "Сатира",
    "humor_verse": "Юмористические стихи, басни",
    "limerick": "Частушки, прибаутки, потешки",
    "literature_18": "Классическая проза XVII-XVIII веков",
    "literature_19": "Классическая проза ХIX века",
    "literature_20": "Классическая проза ХX века",
    "love": "Любовные романы",
    "love_contemporary": "Современные любовные романы",
    "love_detective": "Остросюжетные любовные романы",
    "love_erotica": "Эротическая литература",
    "love_hard": "Порно",
    "love_history": "Исторические любовные романы",
    "love_sf": "Любовное фэнтези, любовно-фантастические романы",
    "love_short": "Короткие любовные романы",
    "lyrics": "Лирика",
    "magic_school": "Магическая академия",
    "military_history": "Военная история",
    "military_special": "Военное дело",
    "military_weapon": "Военное дело, военная техника и вооружение",
    "modern_tale": "Современная сказка",
    "music": "Музыка",
    "network_literature": "Самиздат, сетевая литература",
    "nonf_biography": "Биографии и мемуары: прочее",
    "nonf_biography_celebrities": "Биографии и мемуары: звезды кино, театра, балета, шоу-бизнеса",
    "nonf_biography_historical": "Биографии и мемуары: исторические персоны",
    "nonf_biography_military_figures": "Военные мемуары",
    "nonf_biography_writers": "Биографии и мемуары: писатели, поэты, драматурги",
    "nonf_criticism": "Критика",
    "nonf_military": "Военная документалистика и аналитика",
    "nonf_publicism": "Публицистика",
    "nonfiction": "Документальная литература",
    "notes": "Партитуры",
    "nsf": "Ненаучная фантастика",
    "org_behavior": "Маркетинг, PR",
    "other": "Неотсортированное",
    "painting": "Живопись, альбомы, иллюстрированные каталоги",
    "palindromes": "Визуальная и экспериментальная поэзия, верлибры, палиндромы",
    "periodic": "Журналы, газеты",
    "poem": "Поэма, эпическая поэзия",
    "poetry": "Поэзия",
    "poetry_classical": "Классическая поэзия",
    "poetry_east": "Поэзия Востока",
    "poetry_for_classical": "Классическая зарубежная поэзия",
    "poetry_for_modern": "Современная зарубежная поэзия",
    "poetry_modern": "Современная поэзия",
    "poetry_rus_classical": "Классическая русская поэзия",
    "poetry_rus_modern": "Современная русская поэзия",
    "popadancy": "Попаданцы",
    "popular_business": "Карьера, кадры",
    "prose": "Проза",
    "prose_abs": "Фантасмагория, абсурдистская проза",
    "prose_classic": "Классическая проза",
    "prose_contemporary": "Современная русская и зарубежная проза",
    "prose_counter": "Контркультура",
    "prose_game": "Детский досуг",
    "prose_history": "Историческая проза",
    "prose_magic": "Магический реализм",
    "prose_military": "Проза о войне",
    "prose_neformatny": "Экспериментальная, неформатная проза",
    "prose_rus_classic": "Русская классическая проза",
    "prose_su_classics": "Советская классическая проза",
    "proverbs": "Пословицы, поговорки",
    "ref_dict": "Словари",
    "ref_encyc": "Энциклопедии",
    "ref_guide": "Руководства",
    "ref_ref": "Справочники",
    "reference": "Справочная литература",
    "religion": "Религия, религиозная литература",
    "religion_budda": "Буддизм",
    "religion_catholicism": "Католицизм",
    "religion_christianity": "Христианство",
    "religion_esoterics": "Эзотерика, эзотерическая литература",
    "religion_hinduism": "Индуизм",
    "religion_islam": "Ислам",
    "religion_judaism": "Иудаизм",
    "religion_orthodoxy": "Православие",
    "religion_paganism": "Язычество",
    "religion_protestantism": "Протестантизм",
    "religion_rel": "Религиозная литература",
    "religion_self": "Самосовершенствование",
    "russian_fantasy": "Российское фэнтези",
    "sci_biology": "Биология, биофизика, биохимия",
    "sci_botany": "Ботаника",
    "sci_build": "Строительство и сопромат",
    "sci_chem": "Химия",
    "sci_cosmos": "Астрономия и Космос",
    "sci_culture": "Культурология",
    "sci_ecology": "Экология",
    "sci_economy": "Экономика",
    "sci_geo": "Геология и география",
    "sci_history": "История",
    "sci_juris": "Юриспруденция",
    "sci_linguistic": "Языкознание, иностранные языки",
    "sci_math": "Математика",
    "sci_medicine": "Медицина",
    "sci_medicine_alternative": "Альтернативная медицина",
    "sci_metal": "Металлургия",
    "sci_oriental": "Востоковедение",
    "sci_pedagogy": "Педагогика, воспитание детей, литература для родителей",
    "sci_philology": "Литературоведение",
    "sci_philosophy": "Философия",
    "sci_phys": "Физика",
    "sci_politics": "Политика",
    "sci_popular": "Образовательная, прикладная, научно-популярная литература",
    "sci_psychology": "Психология и психотерапия",
    "sci_psychology_popular": "Популярная психология",
    "sci_radio": "Радиоэлектроника",
    "sci_religion": "Религиоведение",
    "sci_social_studies": "Обществознание, социология",
    "sci_state": "Государство и право",
    "sci_tech": "Технические науки",
    "sci_textbook": "Учебники и пособия",
    "sci_theories": "Альтернативные науки и научные теории",
    "sci_transport": "Транспорт и авиация",
    "sci_veterinary": "Ветеринария",
    "sci_zoo": "Зоология",
    "science": "Научная литература",
    "screenplays": "Сценарий",
    "sf": "Научная фантастика",
    "sf_action": "Боевая фантастика и фэнтези",
    "sf_cyberpunk": "Киберпанк",
    "sf_detective": "Детективная фантастика",
    "sf_epic": "Эпическая фантастика и фэнтези",
    "sf_etc": "Фантастика",
    "sf_fantasy": "Фэнтези",
    "sf_fantasy_city": "Городское фэнтези",
    "sf_heroic": "Героическая фантастика и фэнтези",
    "sf_history": "Альтернативная история",
    "sf_horror": "Ужасы",
    "sf_humor": "Юмористическая фантастика и фэнтези",
    "sf_industrial_magic": "Производственная магия",
    "sf_litrpg": "ЛитРПГ",
    "sf_mystic": "Мистика",
    "sf_postapocalyptic": "Постапокалипсис",
    "sf_realrpg": "РеалРПГ",
    "sf_social": "Социально-психологическая фантастика",
    "sf_space": "Космическая фантастика",
    "sf_stimpank": "Стимпанк",
    "sf_su": "Советская фантастика",
    "sf_technofantasy": "Технофэнтези",
    "sf_writing": "Научная фантастика",
    "slavic_fantasy": "Славянское фэнтези",
    "song_poetry": "Песенная поэзия",
    "story": "Малые литературные формы прозы: рассказы, эссе, новеллы, феерия",
    "tale_chivalry": "Рыцарский роман",
    "tbg_computers": "Учебные пособия, самоучители",
    "tbg_higher": "Учебники и пособия ВУЗов",
    "tbg_school": "Школьные учебники и пособия, рефераты, шпаргалки",
    "tbg_secondary": "Учебники и пособия для среднего и специального образования",
    "theatre": "Театр",
    "thriller": "Триллер",
    "thriller_mystery": "Триллеры",
    "tragedy": "Трагедия",
    "travel_notes": "География, путевые заметки",
    "unfinished": "Незавершенное",
    "utopia": "Утопия",
    "vaudeville": "Мистерия, буффонада, водевиль",
    "Биографии и мемуары": "Биографии и мемуары",
    "Шпионский Детектив": "Шпионский Детектив",
}


def genre_label(code: str) -> str:
    """Preserve unknown future codes instead of discarding genre metadata."""
    return GENRE_NAMES.get(code, code)
